/**
 * Blog Configuration
 *
 * Edit this file to customize your blog.
 * Generated by `pnpm blog:setup`. Edit freely — setup won't overwrite this file.
 */
const config = {
  // ─── Site ──────────────────────────────────────────────────────────
  title: 'My Blog',
  description: 'A blog about technology',
  locale: 'en',
  siteUrl: '',
  siteLogo: '',
  siteBanner: '',

  // ─── Author ────────────────────────────────────────────────────────
  author: {
    localeName: 'Author Name',
    enName: 'Author Name',
    bio: 'Write a brief introduction about yourself',
    contacts: {
      email: '',
      github: '',
      linkedin: '',
      twitter: '',
      rss: '',
    },
  },

  // ─── Comments (https://giscus.app) ─────────────────────────────────
  giscus: {
    repo: '',
    repoId: '',
    category: 'Comments',
    categoryId: '',
  },

  // ─── Navigation ────────────────────────────────────────────────────
  navigation: [{ href: '/article/list/1', name: 'articles', description: 'all posts' }],
};

export default config;
