#!/bin/bash
# ─── Obsidian Blog Kit — Zero-config setup ───────────────────────────
#
# Usage:  pnpm blog:setup
#
# Auto-detects git config, generates blog.config.ts, initializes vault.
# Edit blog.config.ts to customize.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/common.sh"

banner "Obsidian Blog Kit"

# ─── 1. Environment ─────────────────────────────────────────────────

if ! command -v node &> /dev/null; then
    fail "Node.js not found — install v18+ from https://nodejs.org"
    exit 1
fi
NODE_MAJOR=$(node -v | sed 's/v//' | cut -d. -f1)
[ "$NODE_MAJOR" -lt 18 ] && warn "Node.js $(node -v) — v18+ recommended" || success "Node.js $(node -v)"

if ! command -v pnpm &> /dev/null; then
    fail "pnpm not found — run: corepack enable && corepack prepare pnpm@latest --activate"
    exit 1
fi
success "pnpm v$(pnpm -v)"

# ─── 2. Dependencies ────────────────────────────────────────────────

if [ ! -d node_modules ] || [ package.json -nt node_modules ]; then
    echo -e "\n  ${BLUE}Installing dependencies...${NC}"
    if ! pnpm install --silent; then
        fail "Failed to install dependencies — check network and try again"
        exit 1
    fi
fi
success "Dependencies ready"

# ─── 3. Auto-detect ─────────────────────────────────────────────────

GIT_USER=$(git config user.name 2>/dev/null || echo "")
GIT_EMAIL=$(git config user.email 2>/dev/null || echo "")
GITHUB_REPO=""
GITHUB_USER=""
GISCUS_REPO_ID=""
GISCUS_CAT_ID=""

if command -v git &> /dev/null && git remote get-url origin &> /dev/null 2>&1; then
    REMOTE_URL=$(git remote get-url origin)
    GITHUB_REPO=$(echo "$REMOTE_URL" | sed 's|\.git$||' | awk -F '[/:]' '{print $(NF-1)"/"$NF}')
    GITHUB_USER=$(echo "$GITHUB_REPO" | cut -d'/' -f1)
fi

# Giscus auto-detection via GitHub CLI
if [ -n "$GITHUB_REPO" ] && command -v gh &> /dev/null && gh auth status &> /dev/null 2>&1; then
    OWNER=$(echo "$GITHUB_REPO" | cut -d'/' -f1)
    REPO=$(echo "$GITHUB_REPO" | cut -d'/' -f2)

    GRAPHQL=$(gh api graphql -f query='
        query($o: String!, $r: String!) {
            repository(owner: $o, name: $r) {
                id
                hasDiscussionsEnabled
                discussionCategories(first: 20) { nodes { id name } }
            }
        }
    ' -f o="$OWNER" -f r="$REPO" 2>/dev/null)

    if [ $? -eq 0 ] && [ -n "$GRAPHQL" ]; then
        HAS_DISC=$(echo "$GRAPHQL" | grep -o '"hasDiscussionsEnabled":[a-z]*' | cut -d':' -f2)
        if [ "$HAS_DISC" = "false" ] && [ "$CI" != "true" ] && confirm "Enable GitHub Discussions for Giscus comments?"; then
            gh repo edit "$GITHUB_REPO" --enable-discussions 2>/dev/null
            GRAPHQL=$(gh api graphql -f query='
                query($o: String!, $r: String!) {
                    repository(owner: $o, name: $r) {
                        id
                        discussionCategories(first: 20) { nodes { id name } }
                    }
                }
            ' -f o="$OWNER" -f r="$REPO" 2>/dev/null)
        fi

        GISCUS_REPO_ID=$(echo "$GRAPHQL" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
        GISCUS_CAT_ID=$(echo "$GRAPHQL" | python3 -c "
import sys,json
d=json.load(sys.stdin)
ns=d.get('data',{}).get('repository',{}).get('discussionCategories',{}).get('nodes',[])
for n in ns:
    if n['name'].lower()=='comments': print(n['id']);sys.exit(0)
if ns: print(ns[0]['id'])
" 2>/dev/null)
    fi
fi

# ─── 4. Language & Generate blog.config.ts ────────────────────────────

# Copy from example if config doesn't exist yet
if [ ! -f src/config/blog.config.ts ] && [ -f src/config/blog.config.example.ts ]; then
    cp src/config/blog.config.example.ts src/config/blog.config.ts
fi

if [ ! -f src/config/blog.config.ts ]; then
    echo ""
    select_option "Language" "English" "한국어"
    [ "$SELECT_RESULT" = "한국어" ] && LOCALE="ko" || LOCALE="en"

    # Escape single quotes for TypeScript string literals
    AUTHOR_NAME=$(echo "${GIT_USER:-Author Name}" | sed "s/'/\\\\'/g")
    AUTHOR_EMAIL=$(echo "${GIT_EMAIL}" | sed "s/'/\\\\'/g")
    AUTHOR_GITHUB=""
    [ -n "$GITHUB_USER" ] && AUTHOR_GITHUB="https://github.com/$GITHUB_USER"
    GISCUS_REPO="${GITHUB_REPO}"

    cat > src/config/blog.config.ts << CONFIGEOF
/**
 * Blog Configuration
 *
 * Edit this file to customize your blog.
 * Generated by \`pnpm blog:setup\`. Edit freely — setup won't overwrite this file.
 */
const config = {
  // ─── Site ──────────────────────────────────────────────────────────
  title: 'My Blog',
  description: 'A blog about technology',
  locale: '${LOCALE}',
  siteUrl: '',
  siteLogo: '',
  siteBanner: '',

  // ─── Author ────────────────────────────────────────────────────────
  author: {
    localeName: '${AUTHOR_NAME}',
    enName: '${AUTHOR_NAME}',
    bio: 'Write a brief introduction about yourself',
    contacts: {
      email: '${AUTHOR_EMAIL}',
      github: '${AUTHOR_GITHUB}',
      linkedin: '',
      twitter: '',
      rss: '',
    },
  },

  // ─── Comments (https://giscus.app) ─────────────────────────────────
  giscus: {
    repo: '${GISCUS_REPO}',
    repoId: '${GISCUS_REPO_ID}',
    category: 'Comments',
    categoryId: '${GISCUS_CAT_ID}',
  },

  // ─── Navigation ────────────────────────────────────────────────────
  navigation: [
    { href: '/article/list/1', name: 'articles', description: 'all posts' },
  ],
};

export default config;
CONFIGEOF

    echo ""
    echo -e "  ${BOLD}Generated src/config/blog.config.ts:${NC}"
    [ -n "$GIT_USER" ] && success "Author → $GIT_USER"
    [ -n "$GIT_EMAIL" ] && success "Email → $GIT_EMAIL"
    [ -n "$GITHUB_USER" ] && success "GitHub → https://github.com/$GITHUB_USER"
    [ -n "$GISCUS_REPO_ID" ] && success "Giscus → $GITHUB_REPO"
else
    success "blog.config.ts exists (src/config/)"
fi

# ─── 5. Obsidian vault ──────────────────────────────────────────────

echo ""
if [ -d "posts" ] && [ -d ".obsidian" ] && [ -f "dashboard.md" ]; then
    success "Obsidian vault ready"
else
    QUIET=true LOCALE="${LOCALE:-en}" bash "$SCRIPT_DIR/content.sh"
    success "Obsidian vault created"
fi

# ─── 6. First deploy (optional) ──────────────────────────────────────

echo ""
if confirm "Deploy to Vercel now?"; then
    vercel_deploy "prod"
fi

# ─── Done ────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  ✓ Setup Complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${BLUE}pnpm dev${NC}               Start dev server"
echo -e "  ${BLUE}pnpm blog:deploy${NC}       Deploy to Vercel"
echo -e "  ${BLUE}Edit src/config/blog.config.ts${NC}  Customize your blog"
echo -e "  ${BLUE}Open in Obsidian${NC}       This folder → Make.md Navigator"
echo -e "  ${BLUE}dashboard.md${NC}           Click to open Dashboard"
echo ""
